### ISSUE TITLE
Ver video de datalatam respecto a git y github

### ISSUE THREAD

**Issue by cthed2** [Jalorca/Learn_Git#1]
https://www.youtube.com/watch?v=PSNNbeVUxFc (este despues)

https://www.youtube.com/watch?v=SVzyWV1Iep8 (este primero)

Aca en comentarios dejes tus conclusiones, primero de la herramienta git y github. y después tu análisis del video.

**Comment by Jalorca** [comment]
# Comentario del Video: Uso común de Git - Data Latam - https://www.youtube.com/watch?v=SVzyWV1Iep8 
- Lo que me pareció más interesante con respecto al uso de RStudio, el espacio de trabajo es más amigable y simple para la ejecución de los comandos de Git a través del mismo editor, lo cual hace más visual la ejecución de los pasos en el flujo de trabajo.
- Es necesario comprender el flujo de trabajo en GitHub, es un requisito totalmente indispensable.
# Comentario del Video: Ayuda para solicitudes de fusión en GitHub - Data Latam -https://www.youtube.com/watch?v=PSNNbeVUxFc
- La librería 'usethis' simplifica los pasos para mantener el flujo en el trabajo con GitHub, pero es necesario entender bien los comandos básicos de Git y el entorno de GitHub. Además, muestra de el proceso que realizan las funciones de la librería 'usethis' lo cual ayuda a mantener un seguimiento a lo que se esta ejecutando.

**Comment by cthed2** [comment]
Bien.

¿Qué te parece más fácil desde RStudio, VS Code  o GitBash?

**Comment by Jalorca** [comment]
Para comenzar GitBash y VS Code te ayudan a saber si lo que estas haciendo esta bien o mal, señalándote los errores, cuando ya se tenga practica con los comandos, RStudio te ayuda haciendo el proceso mas amigable y visual, así que al final me parece más fácil RStudio.
